"""
Configuration - System Settings 🎛️

Centralized configuration settings for the Eidosian Refactor system.
Provides constants and settings used throughout the system.
"""

from typing import Dict, List, Pattern
import re

# ╭──────────────────────────────────────────────────────╮
# │  🔍 Analysis Configuration - Detection Parameters    │
# ╰──────────────────────────────────────────────────────╯

# Patterns that suggest logical module boundaries
MODULE_BOUNDARY_PATTERNS = [
    # Comment-based boundaries
    r"# [\-─═]{2,}.*?[\-─═]{2,}",              # Standard dividers: # ----------
    r"# ╭.*?╮\s*# │.*?│\s*# ╰.*?╯",            # Box dividers
    r"#{3,}\s*([A-Za-z0-9_ ]+)\s*#{3,}",       # Title dividers: ### Section ###
    
    # Code-based boundaries
    r"class [A-Z][a-zA-Z0-9]*(\(.*?\))?:",     # Class definitions  
    r"@\w+\s*(\(.*?\))?\s*\n+def ",            # Decorated function groups
]

# Compiled patterns for efficiency
COMPILED_BOUNDARY_PATTERNS = [re.compile(pattern) for pattern in MODULE_BOUNDARY_PATTERNS]

# Semantic indicators for module purpose inference
MODULE_PURPOSE_INDICATORS: Dict[str, List[str]] = {
    "util": ["utility", "helper", "tool", "common"],
    "model": ["model", "entity", "data class", "schema", "structure"],
    "service": ["service", "manager", "handler", "processor"],
    "controller": ["controller", "view", "endpoint", "route"],
    "config": ["config", "setting", "parameter", "environment"],
}

# ╭──────────────────────────────────────────────────────╮
# │  📝 Documentation Generation - Templates             │
# ╰──────────────────────────────────────────────────────╯

MODULE_DOCSTRING_TEMPLATE = '''"""
{module_name} - {module_purpose} {emoji}

{module_description}
"""'''

PACKAGE_INIT_TEMPLATE = '''"""
{package_name} Package - {package_description}

This package was automatically generated by Eidosian Refactor.
{original_source_comment}
"""

__version__ = "0.1.0"

{imports}
'''

README_TEMPLATE = '''# {package_name}

{package_description}

## Modules

{module_list}

## Usage

```python
from {package_import_name} import {example_import}

# Add usage examples here
```

## Original Source

This package was automatically generated from `{source_file}` using Eidosian Refactor.
'''

# ╭──────────────────────────────────────────────────────╮
# │  🧩 System Defaults - Fallback Values                │
# ╰──────────────────────────────────────────────────────╯

DEFAULT_MODULE_EMOJIS = {
    "util": "🛠️",
    "model": "📊",
    "service": "⚙️",
    "controller": "🎮",
    "config": "🔧",
    "core": "🧱",
    "interface": "🖥️",
    "default": "📦"
}

DEFAULT_INDENT = "    "  # 4 spaces
MAX_LINE_LENGTH = 88     # PEP 8 recommendation with a bit of margin
